# Generated by Django 4.2.6 on 2023-11-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antarcticMass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('antarctic_mass', models.FloatField()),
                ('antarcticMass_1sigma_uncertainty', models.FloatField()),
            ],
        ),
    ]
