# Generated by Django 4.2.6 on 2023-11-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sulfur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.FloatField()),
                ('neem', models.FloatField()),
                ('wdc', models.FloatField()),
            ],
        ),
    ]
