# Generated by Django 4.2.6 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='glacierAlgae',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('f', models.IntegerField()),
                ('fm', models.IntegerField()),
                ('par', models.IntegerField()),
                ('y', models.FloatField()),
                ('etr', models.FloatField()),
                ('rep', models.CharField(max_length=10)),
                ('treat', models.CharField(max_length=50)),
                ('npq', models.FloatField()),
                ('etrmax', models.FloatField()),
                ('alpha', models.FloatField()),
                ('ek', models.FloatField()),
            ],
        ),
    ]
