# Generated by Django 4.2.6 on 2023-11-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='microbialSymbionts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('response_unit', models.CharField(max_length=10)),
                ('mean', models.FloatField()),
                ('n', models.IntegerField()),
                ('dispersion_value', models.FloatField()),
                ('dispersion_measure', models.CharField(max_length=10)),
                ('cold_condition', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
                ('infection_status', models.CharField(max_length=10)),
                ('microorganism', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
