# Generated by Django 4.2.6 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alaskaStreamgages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(max_length=10)),
                ('location_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lat_long_type', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('hydrologic_unit', models.IntegerField()),
                ('drainage_area', models.FloatField()),
                ('datum_of_page', models.FloatField()),
                ('datum_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='iceExtent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('extent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='northernClimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('year', models.IntegerField()),
                ('hemisphere', models.CharField(max_length=50)),
                ('average_temperature', models.FloatField()),
                ('east_west', models.CharField(max_length=10)),
            ],
        ),
    ]
