# Generated by Django 4.2.6 on 2023-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_arctic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='simpsonLagoon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_ID', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('mid_sampling', models.DateTimeField()),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('salinity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('radium224', models.FloatField()),
                ('error224', models.FloatField()),
                ('radium223', models.FloatField()),
                ('error223', models.FloatField()),
                ('radium228', models.FloatField()),
                ('error228', models.FloatField()),
                ('radium226', models.FloatField()),
                ('error226', models.FloatField()),
            ],
        ),
    ]
