# Generated by Django 4.2.6 on 2023-11-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salinity', models.FloatField()),
                ('january_temp', models.FloatField()),
                ('june_temp', models.FloatField()),
                ('area', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_of_sea', models.FloatField()),
                ('silt_sulfide', models.FloatField()),
                ('coral_status', models.FloatField()),
            ],
        ),
    ]
