# Generated by Django 4.2.6 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinstrappenguin',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='giantpetrelbird',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
