# Generated by Django 4.2.6 on 2023-11-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gentooPenguin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('date_pair_count', models.DateField()),
                ('total_number_pairs_with_eggs', models.IntegerField()),
                ('total_number_of_pairs_without_eggs', models.IntegerField()),
                ('total_number_of_pairs', models.IntegerField()),
                ('date_chick_count', models.DateField()),
                ('total_number_of_chicks', models.IntegerField()),
                ('total_number_of_eggs', models.IntegerField()),
                ('total_number_of_nests_without_eggs', models.IntegerField()),
                ('date_fledgling_count', models.DateField()),
                ('total_number_of_fledglings', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='coral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
