# Generated by Django 4.2.6 on 2023-11-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0002_alter_chinstrappenguin_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeliepenguin',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_chick_count',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_fledgling_count',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_pair_count',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_chicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_fledglings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_nests_without_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_pairs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_of_pairs_without_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='total_number_pairs_with_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_chick_count',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_pair_count',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_chicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_fledglings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_nests_without_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_pairs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_of_pairs_without_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='total_number_pairs_with_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
