# Generated by Django 4.2.6 on 2023-11-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0003_alter_adeliepenguin_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_fledgling_count',
            field=models.DateField(blank=True, null=True),
        ),
    ]
