# Generated by Django 4.2.6 on 2023-11-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0005_alter_adeliepenguin_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krillbase',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='krillbase',
            name='net_time',
            field=models.DateTimeField(),
        ),
    ]
