# Generated by Django 4.2.6 on 2023-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0006_alter_krillbase_date_alter_krillbase_net_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krillbase',
            name='net_time',
            field=models.CharField(max_length=100),
        ),
    ]
