# Generated by Django 4.2.6 on 2023-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0007_alter_krillbase_net_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_chick_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_fledgling_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adeliepenguin',
            name='date_pair_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_chick_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_fledgling_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gentoopenguin',
            name='date_pair_count',
            field=models.CharField(max_length=100),
        ),
    ]
