# Generated by Django 4.2.6 on 2023-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0008_alter_adeliepenguin_date_chick_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bearAbdominalTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BearID', models.IntegerField()),
                ('datetimeUTC', models.DateTimeField()),
                ('bodyTemp_abdominal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bearBlood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BearID', models.IntegerField()),
                ('datetimeUTC', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ambient_temp', models.FloatField()),
                ('duration', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('mass', models.FloatField()),
                ('measuredTelazol_dose', models.FloatField()),
                ('ALT', models.FloatField()),
                ('Glucose', models.FloatField()),
                ('Sodium', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('WBC_count', models.FloatField()),
                ('Lymphocyte', models.FloatField()),
                ('Neutrophil', models.FloatField()),
                ('Cortisol', models.FloatField()),
                ('Glutamic_acid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bearCapSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BearID', models.IntegerField()),
                ('datetimeUTC', models.DateTimeField()),
                ('Event', models.CharField(max_length=100)),
                ('Rectal_temp', models.FloatField()),
            ],
        ),
    ]
