# Generated by Django 4.2.6 on 2023-11-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_animal', '0009_bearabdominaltemp_bearactivity_bearblood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giantpetrelbird',
            name='date_chick_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='giantpetrelbird',
            name='date_of_nest_count',
            field=models.CharField(max_length=100),
        ),
    ]
